#ifndef PARSER_INCLUDES_CHECKTYPES_H_
#define PARSER_INCLUDES_CHECKTYPES_H_

class CheckTypes {
public:
    enum Type { INTTYPE, INTARRAYTYPE, ARRAYTYPE, NOTYPE, ERRORTYPE,
				OPPLUS, OPMINUS, OPMULT, OPDIV, OPLESS, OPGREATER,
				OPEQUAL, OPUNEQUAL, OPAND };
};

#endif /* PARSER_INCLUDES_CHECKTYPES_H_ */
